version: '3.8'
services:
  dev-db:
    image: postgres:15.2
    container_name: dev-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
